### ISSUE TITLE
I think there are some code bugs.

### ISSUE THREAD

**Issue by Menace-Dragon** [zhutmost/lsq-net#12]
1. Bug in quan\func.py at line 25:
    TypeError: _conv_forward() missing 1 required positional argument: 'bias', 
    while the code is 'self._conv_forward(quantized_act, quantized_weight)'
    
2. Bug in model\resnet_cifar.py at line 124:
    avg_pool2d(): argument 'kernel_size' (position 2) must be tuple of ints, not Tensor,
    while the code is 'F.avg_pool2d(out, out.size()[3])'

If these codes on your machine run without error, I guess bugs may be caused by Pytorch version.
And my Pytorch version is 1.8.1.

**Comment by zhutmost** [comment]
Because Pytorch always modify the API of _conv_forward(), and I have not worked on this project for a long time.

**Comment by zhutmost** [comment]
The last time I tested my code is pytorch 1.5. I am not very sure.

**Comment by Menace-Dragon** [comment]
Thank you.I have dealt with them.

**Comment by kaiqi123** [comment]
Hi Menace-Dragon, how did you solved this issue?

**Comment by kaiqi123** [comment]
> Thank you.I have dealt with them.


Hi Menace-Dragon, how did you solved this issue?
