### ISSUE TITLE
runtime error of backend cpu

### ISSUE THREAD

**Issue by leo19850812** [zhutmost/lsq-net#14]
resnet20_a3w3_cifar10_config.yaml，when run main.py it shows this:
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
Do you maintain this project?

**Comment by zhutmost** [comment]
I guess you are using a new version of torch. Just modify the .view to .reshape. PyTorch modified this API long time ago (maybe last year if I am not wrong).

**Comment by leo19850812** [comment]
Yes，i changed the func view->reshape，it worked. Will you work on LSQ+ future？

**Comment by zhutmost** [comment]
Sorry that currently I have no plan. At least in a short time. I am not a professional algorithm researcher, and I am working other projects recently.

**Comment by zhutmost** [comment]
If you do a pull request, I am glad to accept.

**Comment by crowerly** [comment]
> If you do a pull request, I am glad to accept.

For weights, we can use the (LSQ+)-based initialization policy that `s=max((mean-3*std).abs(), (mean+3*std).abs())/2**(bits-1)`;
For activations, just `2*x.abs().mean()/math.sqrt(2 **(bits-1)-1)` is enough, where x is the _first_ input feature map.
And I also extended LSQ to mixed-precision, if you are interested, we can keep in touch.

**Comment by crowerly** [comment]
> If you do a pull request, I am glad to accept.

In my experiments:
For weights, I use the (LSQ+)-based initialization policy that s=max((mean-3*std).abs(), (mean+3*std).abs())/2**(bits-1);
For activations, just 2*x.abs().mean()/math.sqrt(2 **(bits-1)-1) is enough, where x is the first input feature map.
And I also extended LSQ to mixed-precision, if you are interested, we can keep in touch.

**Comment by 1hunters** [comment]
> If you do a pull request, I am glad to accept.

In my experiments:
For weights, I use the (LSQ+)-based initialization policy that s=max((mean-3*std).abs(), (mean+3*std).abs())/2**(bits-1);
For activations, just 2*x.abs().mean()/math.sqrt(2 **(bits-1)-1) is enough, where x is the first input feature map.
And I also extended LSQ to mixed-precision, if you are interested, we can keep in touch (but the code may take a while to clear up QAQ).

**Comment by zhutmost** [comment]
Cool. Looking forward to your code.
