### ISSUE TITLE
unnecessary if-else or mistake?

### ISSUE THREAD

**Issue by ice-tong** [zhutmost/lsq-net#16]
https://github.com/zhutmost/lsq-net/blob/2c24a96be06d044fa4c7d651727f4574b8d88c86/quan/quantizer/lsq.py#L48-L52

**Comment by zhutmost** [comment]
because the per_channel quantization option is incomplete. 

A newer version is merged to https://github.com/zhutmost/neuralzip, and I removed this feature.

**Comment by zhutmost** [comment]
If you want to quantize per output channel, you need to adjust the hyper parameters. Or the optimizer may not converge.

**Comment by ice-tong** [comment]
Thanks for your reply.
