### ISSUE TITLE
Quantization of bias

### ISSUE THREAD

**Issue by Yonghao-Tan** [zhutmost/lsq-net#22]
I notice that in the quantize function, only the weight of the layer is quantized, the bias is passed directly forward. So should we quantize the bias also?

**Comment by zhutmost** [comment]
1. Ahah, in most cases, the biases of CONV is set to zero. 2. The memory/computation requirement of the biases is not very large (compared with weights).

**Comment by Yonghao-Tan** [comment]
Thank you for your explanation!
