### ISSUE TITLE
your implement of gradient of weights is wrong

### ISSUE THREAD

**Issue by HumberMe** [zhutmost/lsq-net#4]
in the paper, the gradient of weights and the gradient of activations are different.

**Comment by zhutmost** [comment]
I don't get it. Maybe it would be better if you can add more details.

**Comment by zhutmost** [comment]
Do you mean the difference in initialization values?
<img width="1152" alt="Screen Shot 2020-05-11 at 00 44 31" src="https://user-images.githubusercontent.com/20497382/81505297-bbf73b80-9320-11ea-9f28-983bd7e35c16.png">
