### ISSUE TITLE
The difference between the current version and the version several days ago

### ISSUE THREAD

**Issue by liyue2ppy** [zhutmost/lsq-net#6]
Thanks for the code that helps me a lot. I download the code several days ago, and find it was modified 19 hours ago.  The changes includes the core code, lsq.py. I wonder if there is a huge difference between the current version and the old version or just a code optimization. Thanks!

**Comment by zhutmost** [comment]
If you download the code after June 2 and you don't use the validation-set-split, you can ignore the modification after it. The changes after that day mainly include: 1. fix the unbalance issue when splitting the validation set, and 2) add channel-wise quantization support.

**Comment by zhutmost** [comment]
Since this issue is inactive for a long time, close it.
